language: php
sudo: false
php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2
env:
  - SYMFONY_VERSION=~2.7
  - SYMFONY_VERSION=~3.0
  - SYMFONY_VERSION=~4.0
matrix:
  exclude:
    - php: 5.6
      env: SYMFONY_VERSION=~4.0
    - php: 7.0
      env: SYMFONY_VERSION=~4.0

before_install:
  - composer require --no-update symfony/dependency-injection $SYMFONY_VERSION
  - composer require --no-update symfony/config $SYMFONY_VERSION
  - composer require --no-update symfony/yaml $SYMFONY_VERSION

install:
  - composer install --prefer-dist

script:
  - bin/phpunit --coverage-clover build/logs/clover.xml

after_success:
  - bin/test-reporter
